#pragma checksum "C:\PowerSystemMonitoring\Web\PowerSystemMonitoring.Web\Views\PowerSystemLoads\GetAllLoads.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "f6fdb68d4e8c4bb6ba8013c5bf8696110fae67e7"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_PowerSystemLoads_GetAllLoads), @"mvc.1.0.view", @"/Views/PowerSystemLoads/GetAllLoads.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\PowerSystemMonitoring\Web\PowerSystemMonitoring.Web\Views\_ViewImports.cshtml"
using PowerSystemMonitoring.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\PowerSystemMonitoring\Web\PowerSystemMonitoring.Web\Views\_ViewImports.cshtml"
using PowerSystemMonitoring.Web.ViewModels;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"f6fdb68d4e8c4bb6ba8013c5bf8696110fae67e7", @"/Views/PowerSystemLoads/GetAllLoads.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"11041b78a0247bf94d919d496e09aaa0a7d4598d", @"/Views/_ViewImports.cshtml")]
    public class Views_PowerSystemLoads_GetAllLoads : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<PowerSystemMonitoring.Web.ViewModels.PowerSystemLoad.PowerSystemLoadViewModel>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n<div>\r\n    <h1>All loads in Bulgaria</h1>\r\n    <h4>");
#nullable restore
#line 5 "C:\PowerSystemMonitoring\Web\PowerSystemMonitoring.Web\Views\PowerSystemLoads\GetAllLoads.cshtml"
   Write(Model.DateTime);

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</h4>


</div>
<br />
<table class=""table table-bordered"">
    <thead class=""alert-primary"">
        <tr>
            <th scope=""col"">Name</th>
            <th scope=""col"">MW</th>
            <th scope=""col"">MW, %</th>
        </tr>
    </thead>
    <tbody>
");
#nullable restore
#line 19 "C:\PowerSystemMonitoring\Web\PowerSystemMonitoring.Web\Views\PowerSystemLoads\GetAllLoads.cshtml"
         foreach (var unit in Model.Units)
        {

#line default
#line hidden
#nullable disable
            WriteLiteral("            <tr>\r\n                <td>");
#nullable restore
#line 22 "C:\PowerSystemMonitoring\Web\PowerSystemMonitoring.Web\Views\PowerSystemLoads\GetAllLoads.cshtml"
               Write(unit.Name);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                <td>");
#nullable restore
#line 23 "C:\PowerSystemMonitoring\Web\PowerSystemMonitoring.Web\Views\PowerSystemLoads\GetAllLoads.cshtml"
               Write(unit.LoadAbsoluteValute);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                <td>");
#nullable restore
#line 24 "C:\PowerSystemMonitoring\Web\PowerSystemMonitoring.Web\Views\PowerSystemLoads\GetAllLoads.cshtml"
               Write(unit.LoadPercentageValute);

#line default
#line hidden
#nullable disable
            WriteLiteral(" %</td>\r\n\r\n            </tr>\r\n");
#nullable restore
#line 27 "C:\PowerSystemMonitoring\Web\PowerSystemMonitoring.Web\Views\PowerSystemLoads\GetAllLoads.cshtml"
        }

#line default
#line hidden
#nullable disable
            WriteLiteral("        <tr>\r\n            <td class=\"alert-success\">Total load</td>\r\n            <td  colspan=\"2\" class=\"alert-success text-center\"> ");
#nullable restore
#line 30 "C:\PowerSystemMonitoring\Web\PowerSystemMonitoring.Web\Views\PowerSystemLoads\GetAllLoads.cshtml"
                                                           Write(Model.TotalLoad);

#line default
#line hidden
#nullable disable
            WriteLiteral(" MW</td>\r\n          \r\n\r\n        </tr>\r\n\r\n    </tbody>\r\n</table>\r\n\r\n");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<PowerSystemMonitoring.Web.ViewModels.PowerSystemLoad.PowerSystemLoadViewModel> Html { get; private set; }
    }
}
#pragma warning restore 1591
